import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import { Flashlight } from '@/components/Flashlight'

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Eduardo Tavares',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body
        className={`${roboto.className} relative bg-zinc-900 leading-relaxed text-zinc-400 antialiased`}
      >
        <Flashlight />
        <div className="mx-auto min-h-screen max-w-screen-xl px-24">
          <div className="flex justify-between gap-4">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
